### ISSUE TITLE
An SSL error

### ISSUE THREAD

**Issue by linhvovan29546** [KnuffApp/Knuff#100]
Connection failed: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made."

**Comment by linhvovan29546** [comment]
<img width="458" alt="Screen Shot 2022-01-26 at 14 23 07" src="https://user-images.githubusercontent.com/84692183/151120261-af3b5486-cf97-4a24-bfd8-9fccf7fc39ac.png">

**Comment by ghostwolf90** [comment]
me too

**Comment by rcharlton** [comment]
It looks like Knuff's PN cert has expired.

**Comment by LidiaGr** [comment]
the same problem
