### ISSUE TITLE
My Developer Identity Never Shows Up

### ISSUE THREAD

**Issue by jonstoked** [KnuffApp/Knuff#22]
![screen shot 2014-09-16 at 11 22 31 am](https://cloud.githubusercontent.com/assets/385665/4289617/60dd8a2c-3db5-11e4-8879-1056aee7d6c3.png)

I've checked my keychain and I have multiple valid development certificates.  Any ideas how to solve this?

Thanks,
Jon

**Comment by tomaskraina** [comment]
@blommegard I'm having the same issue. I don't get how that dialog is supposed to work. I have my APNS certificates downloaded and I have installed them in Keychain too.

**Comment by blommegard** [comment]
@tomaskraina You need to have he private keys as well, not just the certificate. If you are on the machine that generated they keys, they should show up by automatic, if not, you need to export and import them, usually with a .p12-file
