### ISSUE TITLE
help: invalid token

### ISSUE THREAD

**Issue by nolith** [KnuffApp/Knuff#31]
Hi,
when I try to send a push notification to my development mobile i get the error "There was an error delivering the notificaton 0: Invalid token".

I get my token from my application logs and loaded the "Apple Development IOS Push Services: <appId here>" certificate from keychain.

I've noticed that there's a "Device" drop down list but it's empty.

Thank you

**Comment by blommegard** [comment]
Hi, thanks for using the app!

Did you remove the <> from your log statement?

**Comment by nolith** [comment]
thank you for making it ;)

Yes I removed the <> and also tried with and without spaces.

**Comment by blommegard** [comment]
Do you have a correct certificate/key-pair, that matches the token?

**Comment by nolith** [comment]
I think so.

I've generated a CSR for the Development IOS Push Services and selected my application Id on the apple member center.

Then I downloaded back the certificate and imported it in keychain, where it automatically found the private key generated during the CSR step.

**Comment by blommegard** [comment]
Yeah, that is the correct way. :) Are you sure that you are using the correct version of the app as well? Sandbox/Not Sandbox?

**Comment by nolith** [comment]
At the moment I've generated only the development iOS push service and I'm running the app from XCode so it must be in sandbox

**Comment by blommegard** [comment]
Can you try it out with the new version of Knuff and see if it still doesn't work for you?

**Comment by katunch** [comment]
Had the same problem here. Knuff is saying "400 Bad Device Token" when you choose Sandbox environment. So i've tested it with production environment and the notification will be devlivered to the app. altough while it is connected to the debugger.  Maybe the toggle "Production/Sandbox" is inverted. But i can not confirm that at the moment.

**Comment by roma86** [comment]
@blommegard why it is closed? i have same issue with 1.0.

**Comment by blommegard** [comment]
@roma86 This is usually not a Knuff error. Is the token actually correct? Do you use the correct certificate?

**Comment by roma86** [comment]
@blommegard i am sorry. it looks like i have had wrong meaning about ad hoc distribution, which connect to the production environment. When Knuff switched to production it works for me. 

Who is the producer of "400 invalid token" error message? Does it returned from apns? It point us to the wrong way of debugging since i spent a hours to figure out where is my mistake in converting NSData to hex.

**Comment by blommegard** [comment]
Oh. :(

Yeah, APNS is the producer: https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html

I guess they mean that there is no such token associated with the production environment, and therefore a bad token.
