### ISSUE TITLE
Can't get to work

### ISSUE THREAD

**Issue by jameseisenhauer** [KnuffApp/Knuff#37]
Downloaded app from app store.
ios 9.2.1 iphone 6
downloaded zip file from release here on github
iphone on wifi with mac

open app on phone - approve sending of notifications
open app on mac see device list choose device
tap "push" button - no notification
close knuff app  on phone
tap "push" button - no notification

You see anything I am doing wrong?

Thanks!

**Comment by blommegard** [comment]
Hi! Thanks for trying it out!

Did you switch to "Knuff iOS" at the top in the Mac app?

**Comment by fruitcoder** [comment]
I have the very same problem :/ "Knuff iOS" is selected!

**Comment by jameseisenhauer** [comment]
Yes Knuff iOS is selected  thanks

**Comment by blommegard** [comment]
If you have a look at the notification settings for the app, it is stil allowed there?

**Comment by jameseisenhauer** [comment]
Yes I doubled checked.  I also installed on my ipad and no luck there as well.  If there is some debug data you wish I could build each app and provide just let me know.  Thanks

**Comment by blommegard** [comment]
Ok, so it should be the OSX app then. If you open Keychain Access, do you have keys/cert for com.madebybowtie.Knuff-iOS?
Of so, does it work to choose "Custom" at the top and the select that cert?

**Comment by blommegard** [comment]
Another reason can be that your firewall is blocking it, read more about that [here](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html).

**Comment by jameseisenhauer** [comment]
Ok so that worked.  Choosing custom, selecting com.madebybowtie.Knuff-iOS cert, selecting production now the notifications are being received   Thanks!

**Comment by commando24** [comment]
com.madebybowtie.Knuff-iOS is expired? what should i do?

**Comment by blommegard** [comment]
@commando24 Have you downloaded version 1.1?

**Comment by commando24** [comment]
Version 1.0 (1) i have this version.

**Comment by commando24** [comment]
i have downloaded new version 1.1.

**Comment by hezhizhen** [comment]
I have done all the steps above, but it still does not work.

**Comment by commando24** [comment]
@hezhizhen have you added knuff framework in your app?

**Comment by hezhizhen** [comment]
@commando24 the token has been detected. do I still need to import the framework?

**Comment by hezhizhen** [comment]
<img width="475" alt="2017-03-07 15 57 54" src="https://cloud.githubusercontent.com/assets/7611700/23647074/db593a92-034e-11e7-87fe-6f7d2a53ad9e.png">

it seems all right, but when i click the button "push", nothing happens

**Comment by commando24** [comment]
sometimes i don't work.try to delete the app and install it again.

**Comment by commando24** [comment]
@hezhizhen yeah it needs token .

**Comment by blommegard** [comment]
@hezhizhen You are trying to push to [Knuff iOS](https://itunes.apple.com/us/app/knuff-the-apns-debug-tool/id993435856?mt=8). Is this really your intention? It seems you want to push to an own app.
If not you have to select the correct identity by pressing the `Choose…` button.

Regarding the framework, you dont need it if you already have the token.

**Comment by hezhizhen** [comment]
@blommegard yeah, I want to push to my ios device. as for the token, when Knuff IOS is opened, I can choose the token by click the `Devices` on my Macbook's screen. But I see nothing in my iphone's screen. Anything else should I do?

**Comment by hezhizhen** [comment]
@commando24 I have deleted the app and re-downloaded the latest release of it. But it doesn't work still

**Comment by blommegard** [comment]
@hezhizhen You should be good to go, have you suspended (closed down) the iOS app? Any difference when you select `Knuff iOS` on the segmented control in the top?

**Comment by hezhizhen** [comment]
@blommegard I have closed down the screen, but before I click the button `Push`, I unlock the screen and keep the IOS app open. 
The only difference between `Custom` tab and `Knuff iOS` tab is the procedure of choosing an identity - the former tab has it and the latter tab doesn't have it.

**Comment by blommegard** [comment]
@hezhizhen you should not have the iOS app open, it should be closed down, pushing to a locked phone works just fine as well.
Yeas, I know the difference, choosing `Knuff iOS` makes sure it is the correct identity, but both should work assuming you are selecting the correct one in `Custom`.

**Comment by hezhizhen** [comment]
@blommegard I closed down the app and locked the screen, and it still did not work.
I wonder if we could choose a more instant way of communicating and then post the reason here.

**Comment by sena1or** [comment]
@hezhizhen the same problem exist for me

Have you found solution?
Nothing happens for knuff and custom apps...

**Comment by hezhizhen** [comment]
@sena1or Thank you for your comments.
