### ISSUE TITLE
Push being sent twice

### ISSUE THREAD

**Issue by avielg** [KnuffApp/Knuff#38]
Every time I send a push (using the Knuff iOS app) I get it twice, with about 1-2 seconds delta.
Tried it multiple times and it always comes twice...

Generally though - ingenious idea and extremely easy to kick off with the iOS app!

**Comment by blommegard** [comment]
Thanks for trying it out!

I noticed this as well but didn't spend that much time on it because I thought it only happened on my dev device and had something to do with all the versions of the app I had installed.

Will spend some time investigating more now, thanks! :)

**Comment by blommegard** [comment]
This seems to be an Apple issue: https://forums.developer.apple.com/thread/28115
I only get it on the home screen and only since 9.2.
