### ISSUE TITLE
400: DeviceTokenNotForTopic

### ISSUE THREAD

**Issue by bigParis** [KnuffApp/Knuff#39]
I download Knuff from this page https://github.com/KnuffApp/Knuff/releases, but when I test my push on my iphone, I get an error 400:DeviceTokenNotForTopic. 
I have set the tab to "Knuff ios", is there something wrong with my deviceToken?
When I choose "Custom" tab, and select "Sandbox", it shows BadDeviceToken

**Comment by bigParis** [comment]
In addition, I git your code, but still not work, <Fragaria/Fragaria.h> is not found. I have pod update successfully with this note:
Analyzing dependencies
Downloading dependencies
Installing KVOController (1.0.3)
Installing Mantle (2.0.6)
Installing pop (1.0.8)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 3 dependencies from the Podfile and 3 total pods installed.
How to use Knuff?

**Comment by blommegard** [comment]
You can get an explanation for the error codes [here](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html).

What are you trying to do? Do you try to send push messages to the Knuff iOS app or an app you are developing yourself?

**Comment by bigParis** [comment]
@blommegard I try to push messages to an app developed by myself.

**Comment by bigParis** [comment]
@blommegard The Knuff client is install on my macbook.Will this work?

**Comment by blommegard** [comment]
Running the binary downloaded from [releases](https://github.com/KnuffApp/Knuff/releases) should work just fine, you don't have to clone and build it yourself.

How do you get the device token, is the certificate matching the app-id, tried both sandbox and production?

**Comment by bigParis** [comment]
@blommegard I get the device token from Apple Sever callback didRegisterForRemoteNotificationsWithDeviceToken, and my  device token is c91ea1071e33a075f3364b7afb786ae4e759480d3b773630d9650c5f78570a42

the code is:
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
    NSString* token = [NSString stringWithFormat:@"%@",deviceToken];
    
    std::string strToken([token UTF8String], [token length]);
    GameLogic::getInstance()->getPushLogic()->handlePushToken(strToken);
    
    MFAppLogInfo(@"didRegisterForRemoteNotificationsWithDeviceToken:%s",strToken.c_str());
    
    [self clearRemotePushNotifications];
}

handlePushToken will do something myself relative to token

**Comment by blommegard** [comment]
So with "custom" selected and the correct certificate selected, you still get "BadDeviceToken"?

**Comment by bigParis** [comment]
The truth is I send messages on mac, and I want to get a push on my iphone which has already installed the app developed by myself, I still need certificate? In "Knuff IOS" tab there is no way to add a certificate. I should use "custom" and add a certificate?

**Comment by blommegard** [comment]
Yes, you need the certificate generated for your app, that is the one your server uses to send notifications to your users.

**Comment by bigParis** [comment]
The procedure is my server sends messages to  Apple push center(or something like this), and Apple push center pass it to me, I work for an organization, I could't get the certificate from my company. The certificate is used to publish app? In other words how can I get the right certificate?

**Comment by blommegard** [comment]
You need to get the certificate from your company or generate a new one for your app at the [Apple Developer Portal](https://developer.apple.com/).

**Comment by bigParis** [comment]
Thank you for your reply, I use your Knuff client on macbook to push message to Knuff IOS on iphone, it is OK. Probably because I use your push certificate, so I must replace it to my push certificate if I want to push on my app on iphone.
