### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by aventurella** [KnuffApp/Knuff#42]
The device tokens per-app differ, or at least that is how I understood them. In fact, using the device token under the Knuff too to attempt to push to another app generates a "Bad Device Token" error when attempting to push.

Logging the token from my app however, and copy/pasting and attempting to push works wonderfully.

So I feel like this statement is a little bit deceptive in the Readme:

```
Get the device token automatically; forget about manually retrieving the 
device token through logging or similar techniques. Even more useful
when not in sandbox mode
```

Yes, it does this, but it appears to only do it for the Knuff app.

Actually I just found this:
https://github.com/KnuffApp/Knuff-Framework

That solves the problem, it should be linked from the README to make users aware.

**Comment by blommegard** [comment]
Yes that is correct, you can not use a token retrieved from the Knuff iOS app to push to another app.

To automatically get the token from your app you should have a look at [Knuff-Framework](https://github.com/KnuffApp/Knuff-Framework).

I will update the readme to make it even more clear.
