### ISSUE TITLE
This app store app might be copying off you

### ISSUE THREAD

**Issue by aventurella** [KnuffApp/Knuff#44]
https://itunes.apple.com/us/app/apns-tool/id963558865?mt=12

Seems like it's a direct copy of this app, down to the UI.

**Comment by blommegard** [comment]
I think [this one](https://itunes.apple.com/us/app/apns-pusher/id683948849?mt=12) is more of a copy, even took the previous name of this project. :)

Doesn't really mater tho, just aiming to make the best one.
