### ISSUE TITLE
Fragaria.h Not Found

### ISSUE THREAD

**Issue by loretoparisi** [KnuffApp/Knuff#45]
I have tried to add Fragaria to the Podfile, but it didn't work properly.

**Comment by blommegard** [comment]
Fragaria is imported as a [git submodule](https://git-scm.com/docs/git-submodule), `submodule init/update` would do it for you!

**Comment by loretoparisi** [comment]
yep sorry I thought everything was as a Pod. It worked, I just had to set min deployment target to 10.10 (I have Yosemite).
