### ISSUE TITLE
Knuff can't find my identify

### ISSUE THREAD

**Issue by angelmic** [KnuffApp/Knuff#47]
Hi, the Knuff looks great but I download my push notification certificates from iOS member center. Then import the .cer file to my keychain app but no matter how I try, the Knuff can't find it. Do you have any suggestion ?

**Comment by blommegard** [comment]
You need bot the certificate and the private key to sign the payload.

It only exists on the computer that generated the signing request, or if someone exported it from that machine, for example as a .p12-file.

**Comment by angelmic** [comment]
Thanks a lot. I got it !
