### ISSUE TITLE
Cannot find the devices tab for the automatic retrieving of the token

### ISSUE THREAD

**Issue by lorenzOliveto** [KnuffApp/Knuff#49]
I cannot find a way to detect the token automatically, I installed the Knuff framework with CocoaPods but I don't find the device section described in the docs.

**Comment by blommegard** [comment]
Is the App ID you are using enabled for push notification? Are you using the correct provisioning profile?

**Comment by lorenzOliveto** [comment]
Yes, everything works if I send the notification from the server. 
I was trying to use the Knuff app to debug the notifications payload before implementing it server side.

**Comment by blommegard** [comment]
Ok, so it is only the detection the doesn't work? Actually sending notifications works?
Ara you on the same wifi network?

**Comment by lorenzOliveto** [comment]
Now I see it, they were under different networks. 
Thank you so much for your help!
