### ISSUE TITLE
clone Fragaria failed

### ISSUE THREAD

**Issue by MarginBS** [KnuffApp/Knuff#50]
Here is the command lines in Terminal
------
git submodule update --init --recursive
Cloning into 'Vendor/Fragaria'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:shysaur/Fragaria.git' into submodule path 'Vendor/Fragaria' failed
------
by the way, can author add some description for doing "git submodule" command  for the repo "Fragaria" into the README.md,i think it will be helpful.
------
best wishes

**Comment by blommegard** [comment]
`➜ git clone git@github.com:KnuffApp/Knuff.git
Cloning into 'Knuff'...
Warning: Permanently added the RSA host key for IP address '192.30.252.120' to the list of known hosts.
remote: Counting objects: 1026, done.
remote: Total 1026 (delta 0), reused 0 (delta 0), pack-reused 1026
Receiving objects: 100% (1026/1026), 4.16 MiB | 542.00 KiB/s, done.
Resolving deltas: 100% (569/569), done.
Checking connectivity... done.
➜ cd Knuff
➜ git submodule init
Submodule 'Vendor/Fragaria' (git@github.com:shysaur/Fragaria.git) registered for path 'Vendor/Fragaria'
➜  git submodule update
Cloning into 'Vendor/Fragaria'...
remote: Counting objects: 5940, done.
remote: Total 5940 (delta 0), reused 0 (delta 0), pack-reused 5940
Receiving objects: 100% (5940/5940), 7.02 MiB | 808.00 KiB/s, done.
Resolving deltas: 100% (4002/4002), done.
Checking connectivity... done.
Submodule path 'Vendor/Fragaria': checked out '97fddc12260a058b967295ee8f07de91c0f05b5a'

Works just fine here, have you added your ssh key to github?

**Comment by MarginBS** [comment]
get it,it's definitely my ssh key's thing .  u r nice!
