### ISSUE TITLE
iOS 10 HTTP/2 apns-collapse-id header

### ISSUE THREAD

**Issue by chebur** [KnuffApp/Knuff#51]
APNS now provides a new header `apns-collapse-id` to support notifications collapsing on iOS 10. Can you support this feature in your app?

**Comment by blommegard** [comment]
Fantastic news, will have a look at the session right away!

**Comment by jahnaviwisdom** [comment]
@blommegard  can you please tell me how to use in headers from backend service? Currently im using this but not working
 $headers = array(
            'Authorization: key=' . $FIREBASE_API_KEY,
            'Content-Type: application/json',
                         'apns-collapse-id':'1'
        );
