### ISSUE TITLE
Device token feature not working

### ISSUE THREAD

**Issue by brandtdaniels** [KnuffApp/Knuff#53]
I don't see how to get this feature working with 1.0 (1)

"Get the device token automatically; forget about manually retrieving the device token through logging or similar techniques. Even more useful when not in sandbox mode"

**Comment by blommegard** [comment]
Are you using https://github.com/KnuffApp/Knuff-Framework in the iOS app?

**Comment by brandtdaniels** [comment]
No, I didn't see that part. My apologies.

**Comment by commando24** [comment]
I used knuff-framework in my application. and i am getting token from didRegisterForRemoteNotificationsWithDeviceToken method in appDelegate and when i am using this in custom token .i am getting this error.
<img width="478" alt="screen shot 2016-11-07 at 5 09 39 pm" src="https://cloud.githubusercontent.com/assets/15805487/20056582/06d9d2b2-a50d-11e6-9c76-29909f97d61a.png">

**Comment by blommegard** [comment]
I can see in the screenshot that you are using the "Production" environment. If you are getting the token from `didRegisterForRemoteNotificationsWithDeviceToken` using the debugger you should be using the "Sandbox" environment.

A token is considered bad if used in the incorrect environment. (https://developer.apple.com/library/prerelease/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW1)

**Comment by commando24** [comment]
As you suggested i tried that with "sandbox" environment.now i getting different error.
<img width="478" alt="screen shot 2016-11-07 at 5 32 18 pm" src="https://cloud.githubusercontent.com/assets/15805487/20057183/30572b5a-a510-11e6-969c-ba1dbbf4fba9.png">

**Comment by blommegard** [comment]
Either you are affected by https://github.com/KnuffApp/Knuff/issues/33 or you have selected a certificate form your keychain that is not accosiated with the app you are trying to send a push message to.

**Comment by commando24** [comment]
yeah i had selected wrong certificate.now its working .thanks :) 👍

**Comment by blommegard** [comment]
Great to hear!
