### ISSUE TITLE
Getting pull error

### ISSUE THREAD

**Issue by abhi2412shek** [KnuffApp/Knuff#60]
Fragaria/Fragaria.h file not found. i updated the pod aswell

**Comment by blommegard** [comment]
See https://github.com/KnuffApp/Knuff/issues/59

**Comment by abhi2412shek** [comment]
i tried it.. but failed with error

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:shysaur/Fragaria.git' into submodule path 'Vendor/Fragaria' failed

**Comment by blommegard** [comment]
You need to have a SSH key registered with your GitHub account to be able to check bout the this submodule, do you have that?
