### ISSUE TITLE
Problem with certificates

### ISSUE THREAD

**Issue by gperdomor** [KnuffApp/Knuff#67]
I don't know why but i can't choose a certificate
<img width="525" alt="screen shot 2017-03-21 at 10 03 41 am" src="https://cloud.githubusercontent.com/assets/371939/24148518/f83ca3ae-0e1d-11e7-9842-2ab3b3ce23d0.png">

**Comment by blommegard** [comment]
Looks like you only have the certificate and not the private key to compose the identity.

**Comment by gperdomor** [comment]
@blommegard thanks, solved
