### ISSUE TITLE
Can't send custom Payload other than APS

### ISSUE THREAD

**Issue by guhan0** [KnuffApp/Knuff#69]
Please add a provisioning to send a custom payload along with APS key.

**Comment by blommegard** [comment]
Hi!

I'm not really sure what you mean, can you elaborate?

**Comment by guhan0** [comment]
I can send a payload like 

> {
	"aps":
 	{
		"alert":"Testing.. (59)",
		"badge":10,
		"category":"MAIL",
		"content-available":1,
		"mutable-content":1,
		"sound":"default"
	}
}

but not like  with a additional payload than APS

> {
	"aps":
 	{
		"alert":"Testing.. (59)",
		"badge":10,
		"category":"MAIL",
		"content-available":1,
		"mutable-content":1,
		"sound":"default"
	};
      "addInfo":
      { 
        "threadId":"0"
      }
}

**Comment by JanC** [comment]
Your JSON is malformed. The same problem as in your ticket you created in NWPuser

https://github.com/noodlewerk/NWPusher/issues/52

```
{
  "aps": {
    "alert": "Testing.. (70)",
    "badge": 10,
    "category": "MAIL",
    "content-available": 1,
    "mutable-content": 1,
    "sound": "default"
  },
  "addInfo": {
    "testKey": "TestValue"
  }
}
```

**Comment by blommegard** [comment]
Tanks for helping out @JanC :)
