### ISSUE TITLE
400: BadDeviceToken

### ISSUE THREAD

**Issue by LiuAndGang** [KnuffApp/Knuff#71]
您好，我在用kunff的时候，在SandBox的模式下能收到推送，但是在Production的模式下会报错。错误信息如下：400: BadDeviceToken，这是什么原因呢？请赐教，谢谢！
<img width="505" alt="wx20170523-175945 2x" src="https://cloud.githubusercontent.com/assets/26717077/26349193/a592dd62-3fe1-11e7-83c5-7497b156856b.png">

**Comment by pbeast** [comment]
Same here. Any news?

**Comment by blommegard** [comment]
My guess is that you are using an incorrect certificate or token.
Are you sure its the correct ones?

**Comment by pbeast** [comment]
Sorry for bothering. I already found the issue - it was wrong (expired) certificate.

**Comment by jihengcong** [comment]
I'll show BadDeviceToken in production mode, and I'll show DeviceTokenNotForTopic in Sandbox mode
