### ISSUE TITLE
Choose pem instead of an identity

### ISSUE THREAD

**Issue by buttifabio** [KnuffApp/Knuff#73]
It would be nice to have the possibility to send push notifications only having a pem.
Currently if i add a pem to my keychain it doesn't shows up as an identity in the _choose_ dialog.

**Comment by blommegard** [comment]
Are you sure that the `.pem` includes the private key as well?

**Comment by buttifabio** [comment]
I generated it automatically with [fastlane/pem](https://github.com/fastlane/fastlane/tree/master/pem) so no, the private key is not included.

I've just seen [this paragraph](https://github.com/fastlane/fastlane/tree/master/pem#note-about-empty-p12-passwords-and-keychain-accessapp) in fastlane/pem, so probably i have to do like that to import p12 with private key.

Why does Knuff need the private key? To send a push notification my server just need a pem certificate with only the public key; am I wrong?

Thank you

**Comment by blommegard** [comment]
No, you still need the private key when sending you messages from a server.
