### ISSUE TITLE
BadDeviceToken

### ISSUE THREAD

**Issue by jihengcong** [KnuffApp/Knuff#76]
![lalpby0v4qsnmapnaz7naew_492_414 png_620x10000q90g](https://user-images.githubusercontent.com/15802247/32430976-889f09de-c30c-11e7-9252-e9c2b2449591.jpg)
what's this?

**Comment by jihengcong** [comment]
What caused this？It's OK for me to let someone use this token to test me

**Comment by blommegard** [comment]
This mig help: https://github.com/KnuffApp/Knuff/issues/71

**Comment by jihengcong** [comment]
if I select Sandbox ,it's show me DeviceTokenNotForTopic

**Comment by blommegard** [comment]
The explanation for the different error messages can be found here: https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html

My guess is that you hare using the wrong certificate / token combo, might be an outdated/invalidated cert, open Keychain Access and have a look at the certificate.

**Comment by jihengcong** [comment]
Thank you
