### ISSUE TITLE
Can't select identity - list is empty

### ISSUE THREAD

**Issue by zapjonny** [KnuffApp/Knuff#77]
I do have several identities but nothing shows up. This all used to work. Just installed this after reformatting and installing High Sierra. Is this a High Sierra issue? I haven't had this problem before.

![screen shot 2017-11-17 at 15 23 50](https://user-images.githubusercontent.com/20237481/32932378-5eb65d50-cbab-11e7-96a2-d31b1e2f41b1.png)

MacOS Sierra
10.13.1 (17B48)

**Comment by blommegard** [comment]
So you do have the private key AND the certificate in the keychain?

**Comment by zapjonny** [comment]
Yes I have lots of them. I'm building apps every day.

**Comment by zapjonny** [comment]
Tried to debug this, but it seems that `SFChooseIdentityPanel` is part of macOS SDK and maybe this is a bug in the SDK or somewhere...

**Comment by blommegard** [comment]
I installed High Sierra today and tried it out, my list is not empty:
<img width="590" alt="screenshot 2017-11-20 20 36 18" src="https://user-images.githubusercontent.com/86447/33037674-9dba08e2-ce32-11e7-9be0-f7496e324ee3.png">

**Comment by zapjonny** [comment]
I probably made some simple mistake. I'll try to reinstall those certificates and report back if there is some problem.
