### ISSUE TITLE
Doesn't show any certificates when choosing an identity

### ISSUE THREAD

**Issue by mluisbrown** [KnuffApp/Knuff#79]
I have added a an identity cert (.pem file) to my keychain but when I click on Choose to choose an identity I get nothing:

![knuff](https://user-images.githubusercontent.com/4175766/37607213-5629d312-2b8f-11e8-8586-59813750be3a.png)

Also, if I dismiss that dialog and click on Choose again, nothing happens. 

Version 1.2 (3)

**Comment by blommegard** [comment]
Hi!

Does the .pem contains both the identity and cert? What does it looks like in Keychain Access.app?

**Comment by mluisbrown** [comment]
In the Keychain Access app I can see 2 entries for it in "Certificates":

`Apple Push Services: com.<company name etc>`
`VoiP Services: com.<company name etc>`

I can use the `.pem` file with the [Houston command line tool](https://github.com/nomad/houston#command-line-tool) and it works fine.

I'm not the only person on our team with this issue.

**Comment by blommegard** [comment]
But you can see the identity (private key) in Keychain Access.app as well?
Visualised like this: 
<img width="634" alt="screenshot 2018-03-20 10 45 25" src="https://user-images.githubusercontent.com/86447/37647163-e4537656-2c2b-11e8-8b86-6420edcd13d1.png">

**Comment by mluisbrown** [comment]
No, I cannot see the private key in Keychain Access, although I can see that it's there in the `.pem` file

**Comment by blommegard** [comment]
Then its not imported correctly into the Keychain, and Knuff can't access it.
The easiest way to export / import an identity is via the .p12-format.

**Comment by mluisbrown** [comment]
Well, I only have the `.pem` file. I imported it into Keychain by double-clicking on the file. My solution is to use Houston instead 🤷🏼‍♀️

**Comment by blommegard** [comment]
For further reference, what you could do is convert the `.pem` file to a `.p12` and then import it (make sure to type a password, otherwise Keychain Access.app will not import it):

`openssl pkcs12 -export -inkey cert.pem -in cert.pem -name Identity -out Identity.p12`

I would appreciate if you have the time to try it out and verify that it works. :)

**Comment by mluisbrown** [comment]
Ok, after converting the `.pem` to a `.p12` I could import it and then Knuff could see it and it worked ok.

**Comment by blommegard** [comment]
Thanks! I will add it to the readme!
