### ISSUE TITLE
No error callback when app is deleted

### ISSUE THREAD

**Issue by userException** [KnuffApp/Knuff#80]
Hi, I must say this is a very cool utility but when I delete the app form my device and try to send a push to that app, I was expecting a badd token (400 or 410 error code). Is this the expected behavior?

**Comment by blommegard** [comment]
Knuff doesn't have any logic by itself and just reflects the APNS environment.
Might be that it's an app in the sandbox?

**Comment by userException** [comment]
Yes, its a tesflight app but the push is made via prod certificates, does testflight app makes a difference?
