### ISSUE TITLE
Apple Push Services: com.madebybowtie.Knuff-iOS expired

### ISSUE THREAD

**Issue by Creolophus** [KnuffApp/Knuff#81]
Apple Push Services: com.madebybowtie.Knuff-iOS expired

Expired: Sunday, March 10, 2019 at 05:48:52 China Standard Time

**Comment by blommegard** [comment]
That is true, thanks fot the note!

**Comment by victorBaro** [comment]
Any solutions?

**Comment by oliveiraCode** [comment]
I saw the error is there.

**Comment by zinwalin** [comment]
any update?

**Comment by Serena1993** [comment]
+1

**Comment by blommegard** [comment]
This should be fixed with [1.3](https://github.com/KnuffApp/Knuff/releases/tag/v1.3).
