### ISSUE TITLE
Error delivering notification

### ISSUE THREAD

**Issue by huangzhigangxg** [KnuffApp/Knuff#82]
Connection failed: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9800, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x60c00045ba50 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9800, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9800}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://api.push.apple.com/3/device/7fecc20ebe844aa41decd62c4fd3a03422f29afb5b8654e66336e607ffd99fd5, NSErrorFailingURLStringKey=https://api.push.apple.com/3/device/7fecc20ebe844aa41decd62c4fd3a03422f29afb5b8654e66336e607ffd99fd5, _kCFStreamErrorDomainKey=3}

**Comment by blommegard** [comment]
I suppose you are trying to send a message to the Knuff iOS app? The certificate has expired and I will submit an update soon. Tracked in https://github.com/KnuffApp/Knuff/issues/81
