### ISSUE TITLE
build with a error: Unable to resolve build file: XCBCore.BuildFile (namedReferencesCannotBeResolved) (in target 'Knuff')

### ISSUE THREAD

**Issue by chaocaiwei** [KnuffApp/Knuff#83]
error: Unable to resolve build file: XCBCore.BuildFile (namedReferencesCannotBeResolved) (in target 'Knuff')

run on macOS 10.15 Beta

**Comment by linhaosunny** [comment]
I got the same problem

**Comment by little-dandan** [comment]
me too

**Comment by brunomunizaf** [comment]
Same, XC 11.3.1 11C504
Catalina 10.15.2

**Comment by blommegard** [comment]
This seems to work now in Xcode 11.4.
